env:
  global:
  - BRANCH_TO_TEST=$TRAVIS_BRANCH
  matrix:
  #- ADDRESS_MODEL=32
  - ADDRESS_MODEL=64
language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python-yaml
    - gcc-6
    - g++-6
before_script:
    - PROJECT_TO_TEST=`basename $TRAVIS_BUILD_DIR`
    - cd $HOME
    - wget -O boost_1_64_0.tar.gz https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz
    - tar -xf boost_1_64_0.tar.gz > /dev/null
    - BOOST=$HOME/boost_1_64_0
    - cd $BOOST
    - "./bootstrap.sh"
    - "./b2 headers"
    - cd $TRAVIS_BUILD_DIR
    - MW_TEST=$HOME/mw.test
    - git init $MW_TEST
    - cd $MW_TEST
    - if [ $(BRANCH_TO_TEST) = "master" ]; then
      MW_BRANCH=master; 
      else MW_BRANCH=develop; fi
    - git remote add --no-tags -t $MW_BRANCH origin https://github.com/mw-sc/mw.test.git
    - git fetch --depth=1
    - git checkout $MW_BRANCH
    - git submodule update --init --merge
    - git remote set-branches --add origin $MW_BRANCH
    - git pull --recurse-submodules
    - git submodule update --init
    - git checkout $MW_BRANCH
    - git submodule foreach "git reset --quiet --hard; git clean -fxd"
    - git reset --hard; git clean -fxd
    - git status
    - echo "Removing mw.wrap"
    - rm -rf $MW_TEST/wrap
    - mv $TRAVIS_BUILD_DIR/../$PROJECT_TO_TEST $MW_TEST/wrap
    - cp user-config.travis.jam user-config.jam
    - cd ./wrap/test
script:
- $BOOST/b2 release -sBOOST_ROOT=$BOOST define=MW_TRAVISCI_BUILD toolset=gcc-6 linkflags="-ldl -pthread" -sBOOST_BUILD_PATH=. -j4 address-model=$ADDRESS_MODEL cxxflags=-fno-inline
after_success:
    # Copying Coveralls data to a separate folder
    - mkdir -p $TRAVIS_BUILD_DIR/coverals
    - find ../../../bin.v2/ -name "*.gcda" -exec cp "{}" $TRAVIS_BUILD_DIR/coverals/ \;
    - find ../../../bin.v2/ -name "*.gcno" -exec cp "{}" $TRAVIS_BUILD_DIR/coverals/ \;

    # Preparing Coveralls data by changind data format to a readable one
    - git clone https://github.com/linux-test-project/lcov.git lcov_dir
    - GCOV_VERSION=""
    - if [[ "$TOOLSET" == *"-"* ]]; then GCOV_VERSION="--gcov-tool gcov-${TOOLSET#*-}"; fi
    - LCOV="$BOOST/libs/$PROJECT_TO_TEST/test/lcov_dir/bin/lcov $GCOV_VERSION"
    - $LCOV --directory $TRAVIS_BUILD_DIR/coverals --base-directory ./ --capture --output-file $TRAVIS_BUILD_DIR/coverals/coverage.info

    # ... erasing /test/ /example/ folder data
    - cd $BOOST
    - $LCOV --remove $TRAVIS_BUILD_DIR/coverals/coverage.info "/usr*" "*/$PROJECT_TO_TEST/test/*" $IGNORE_COVERAGE "*/$PROJECT_TO_TEST/tests/*" "*/$PROJECT_TO_TEST/examples/*" "*/$PROJECT_TO_TEST/example/*" -o $TRAVIS_BUILD_DIR/coverals/coverage.info

    # ... erasing data that is not related to this project directly
    - OTHER_LIBS=`grep "submodule .*" .gitmodules | sed 's/\[submodule\ "\(.*\)"\]/"\*\/boost\/\1\.hpp" "\*\/boost\/\1\/\*"/g' | sed ':a;N;$!ba;s/\n/ /g'`
    - echo $OTHER_LIBS
    - eval "$LCOV --remove $TRAVIS_BUILD_DIR/coverals/coverage.info $OTHER_LIBS -o $TRAVIS_BUILD_DIR/coverals/coverage.info"

    # Sending data to Coveralls
    - cd $TRAVIS_BUILD_DIR
    - gem install coveralls-lcov
    - coveralls-lcov coverals/coverage.info
