env:
  global:
  - BRANCH_TO_TEST=$TRAVIS_BRANCH
  matrix:
  #- ADDRESS_MODEL=32
  - ADDRESS_MODEL=64
language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - valgrind
    - python-yaml
    - gcc-6
    - g++-6
    - cmake3
    - cmake3-data
before_script:
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    - PROJECT_TO_TEST=`basename $TRAVIS_BUILD_DIR`
    - cd $HOME
    - wget -O boost_1_64_0.tar.gz https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz
    - tar -xf boost_1_64_0.tar.gz > /dev/null
    - BOOST=$HOME/boost_1_66_0
    - cd $BOOST
    - "./bootstrap.sh"
    - "./b2 headers program_options"
    - cd $TRAVIS_BUILD_DIR
script:
- cmake -DENABLE_COVERAGE:BOOL=TRUE -DBOOST_ROOT=$BOOST .
- cmake --build . -- -j4
- ctest
after_success:
    # Copying Coveralls data to a separate folder
    - mkdir -p ./coverals
    - find ../../bin.cpp/wrap -name *.gcda -exec cp "{}" ./coverals/ \;
    - find ../../bin.cpp/wrap -name *.gcno -exec cp "{}" ./coverals/ \;

    # Preparing Coveralls data by changind data format to a readable one
    - git clone https://github.com/linux-test-project/lcov.git lcov_dir
    - GCOV_VERSION="--gcov-tool gcov-6"
    - LCOV="$CPP_TEST/wrap/test/lcov_dir/bin/lcov $GCOV_VERSION --compat-libtool"
    - $LCOV --directory ./coverals --base-directory ./ --capture --output-file ./coverals/coverage.info
    - $LCOV --remove ./coverals/coverage.info "$CPP_TEST/wrap/test/*" "*boost*" "/usr/*" "$CPP_TEST/libs/*" "$CPP_TEST/dbg-runner/*" -o ./coverals/coverage.info

    # Sending data to Coveralls
    - gem install coveralls-lcov
    # https://github.com/okkez/coveralls-lcov/issues/2
    - coveralls-lcov  --source-encoding=ISO-8859-1 ./coverals/coverage.info